### **Сбор и анализ информации о компаниях, которые входят в S&P 500.**   
 ------------------------------------------------------------------------

#### **Цель**  
 ------------------------------------------------------------------------  

Найти и систематизировать информацию о следующих 5-ти компаниях:  

1. **Raytheon Company(RTN)** - Аэрокосмос и оборона  
2. **Walgreens Boots Alliance Inc(WBA)** - Продажа лекарств  
3. **Northrop Grumman Corporation(NOC)** - Аэрокосмос и оборона  
4. **Biogen Inc.(BIIB)** - Биотехнологии  
5. **Becton Dickinson and Company(BDX)** - Здоровье  
  
  
#### **️Исходные данные**  
 ------------------------------------------------------------------------  

1. Ноутбук 
2. Google
3. Kali Linux  
4. Наименование компаний


#### **Общий план выполнения**  
 ------------------------------------------------------------------------  

1. Поиск и сбор информации в интеренете.
2. Поиск и сбор информации с помощью различных утилит.
3. Анализ собранных данных.
4. Составление отчетности.

#### **Результа проделанной работы, предоставлен в таблице ниже**: 
  ------------------------------------------------------------------------ 
  
|    Критерии    |    Raytheon Company           | Walgreens Boots Alliance Inc             |    Northrop Grumman Corporation    |     Biogen Inc.              |    Becton Dickinson and Company    | 
|----------------|:------------------------------|:----------------------------------------:|:----------------------------------:|:----------------------------:|:----------------------------------:|
| Сайт           |  www.raytheon.com/            |www.walgreensbootsalliance.com/           | www.northropgrumman.com/           | www.biogen.com/              | www.bd.com/                        |
| IPNetblook     |74.121.192.0 - 74.121.199.255  | 3.128.0.0 - 3.255.255.255                |	192.0.64.0 - 192.0.127.255         | 34.192.0.0 - 34.255.255.255  | 95.101.24.0 - 95.101.27.255        |
| Местоположение |Уолтем, Массачусетс, США       | Дирфилд (Иллинойс), США                  | Фолс Черч, Вирджиния, США          | Кеймбридж, Массачусетс, США  |  Франклин Лейкс, Нью-Джерси, США   | 
| Телефон        |REDACTED FOR PRIVACY           | +1.8479143246                            | +1.7032802900                      | +1.6176792000                | +001.201.8474000                   | 
| Email админа   |raytheon.com/admin             | domain.manager@walgreens.com             | domainnamecounsel@ngc.com          | domainnamesadmin@biogen.com  | BDNICAdmin@bd.com                  |
| Хостинг        |882ellb0102-vip01.blackmesh.com| ec2-3-232-116-190.compute-1.amazonaws.com| 192.0.66.112(CSC Corporate Domains)| ec2-52-21-176-109.compute-1.amazonaws.com  | a95-101-27-122.deploy.static.akamaitechnologies.com|
| Открытые порты |23,25,80,443,...| 80,443 | 80,443  | 80,443 | 80,443   | 
| Web-технологии |Chartbeat, OWL Carousel, CentOS, Facebook|Acquia Cloud, Hginx, Amazon Web Services, Apache, PHP, Percona, Drupal, Google Analytics,... | WordPress, MySQL, PHP, Hginx, AddToAny, Google Analytics, React, GSAP,... |Red Hat, Apache, OpenSSL, LOdash, jQuery, Java, Typekit, SiteCatalyst,... | jQuery, Google Tag Manager, Hotjar, AppHexus, Matomo, HTTP/2, Lazy.js,...| 

#### **Оценка результатов**  
 ------------------------------------------------------------------------ 
 
Используя открытые источники, такие как Google, и инструменты дистрибутива Kali Linux было найдено немало информации об исследуемых компаниях. 

#### **Вывод**: 
 ------------------------------------------------------------------------ 

Мы научились находить информацию, об интересующих нас компаниях, используя открытые источники и специализированные инструменты поиска. 
