## **Исследование сетевых параметров публичных DNS серверов.**  
 ------------------------------------------------------------------------
 
### **Цель работы**  
 ------------------------------------------------------------------------  

Проанализировать сетевые параметры публичных DNS серверов, сделать мотивированный вывод о предпочтительных серверах  

### **Используемое ПО**  
 ------------------------------------------------------------------------  

Rstudio IDE  
tracert  
ping  
whois  
2ip


### **Исследуемые провайдеры DNS**
 ------------------------------------------------------------------------  
 
1. Google Public DNS
2. Cloudflare DNS
3. OpenDNS
4. Ростелеком МРФ "ЮГ"

### **Варианты решения задачи**
 ------------------------------------------------------------------------  
 
Выполним задание с помощью утилиты tracert


### **Ход работы**
 ------------------------------------------------------------------------  
 
По исследуемым серверам собрать следующие данные:  
- маршрут  
- местоположение каждого узла маршрута к DNS-серверу  
- организацию, владеющую каждым узлом маршрута к DNS-серверу  
- среднюю RTT к DNS-серверу  
- выделить те узлы маршрута, которые вносят наибольшую временную задержку при передаче  

1) **Google Public DNS - 8.8.8.8**  
- маршрут  
```
> tracert 8.8.8.8

Трассировка маршрута к dns.google [8.8.8.8]
с максимальным числом прыжков 30:

  1     2 ms     1 ms     1 ms  TP-LINK.Home [192.168.1.1]
  2    24 ms    27 ms    24 ms  krdr-bras4.ug.ip.rostelecom.ru [178.34.128.7]
  3    23 ms    31 ms    24 ms  178.34.130.6
  4    73 ms    64 ms    58 ms  87.226.181.89
  5    56 ms    57 ms    58 ms  74.125.52.232
  6    59 ms    58 ms    57 ms  108.170.250.66
  7    73 ms    73 ms    73 ms  216.239.50.132
  8    74 ms    72 ms    72 ms  209.85.254.6
  9    74 ms    73 ms    75 ms  216.239.47.203
 10     *        *        *     Превышен интервал ожидания для запроса.
 11     *        *        *     Превышен интервал ожидания для запроса.
 12     *        *        *     Превышен интервал ожидания для запроса.
 13     *        *        *     Превышен интервал ожидания для запроса.
 14     *        *        *     Превышен интервал ожидания для запроса.
 15     *        *        *     Превышен интервал ожидания для запроса.
 16     *        *        *     Превышен интервал ожидания для запроса.
 17     *        *        *     Превышен интервал ожидания для запроса.
 18     *        *        *     Превышен интервал ожидания для запроса.
 19   127 ms   132 ms     *     dns.google [8.8.8.8]
 20   141 ms   201 ms   118 ms  dns.google [8.8.8.8]

Трассировка завершена.
```

- местоположение узлов  

|   Узел  |   Местоположенеи  |
|:-------:|:-----------------:|
|192.168.1.1|Краснодар|
|178.34.128.7|Ставрополь|
|178.34.130.6|Ставрополь|
|87.226.181.89|Москва|
|74.125.52.232|Даллес(США)|
|108.170.250.66|Маунтин-Вью(США)|
|216.239.50.132|Великобритания|
|209.85.254.6|США|
|216.239.47.203|Эмеривилл, Калифорния|
|8.8.8.8|Нью-Йорк|  

- организации


|   Узел  |   Организация     |
|:-------:|:-----------------:|
|192.168.1.1|ROSTELECOM|
|178.34.128.7|ROSTELECOM|
|178.34.130.6|ROSTELECOM|
|87.226.181.89|Rostelecom|
|74.125.52.232|Google LLC|
|108.170.250.66|Google LLC|
|216.239.50.132|Google LLC|
|209.85.254.6|Google LLC|
|216.239.47.203|Google LLC|
|8.8.8.8|Google LLC|  

- среднее RTT к DNS-серверу  
```
>ping 8.8.8.8

Обмен пакетами с 8.8.8.8 по с 32 байтами данных:
Ответ от 8.8.8.8: число байт=32 время=64мс TTL=47
Ответ от 8.8.8.8: число байт=32 время=65мс TTL=47
ОтвОтвет от 8.8.8.8: число байт=32 время=65мс TTL=47
Ответ от 8.8.8.8: число байт=32 время=65мс TTL=47

Статистика Ping для 8.8.8.8:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% по
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 64мсек, Максимальное = 65 мсек, Среднее = 64 мсек
```
- наибольшую временную задержку при передаче вносит 2-й и конечный узел, 8.8.8.8




2) **Cloudflare DNS - 1.1.1.1**  

- маршрут 
```
> tracert 1.1.1.1

Трассировка маршрута к one.one.one.one [1.1.1.1]
с максимальным числом прыжков 30:

  1     3 ms     1 ms     2 ms  TP-LINK.Home [192.168.1.1]
  2    24 ms    23 ms    25 ms  krdr-bras4.ug.ip.rostelecom.ru [178.34.128.7]
  3    24 ms    24 ms    24 ms  178.34.130.6
  4    24 ms    26 ms    24 ms  178.34.130.154
  5    74 ms    76 ms    75 ms  rostel-gw.ip4.gtt.net [77.67.90.97]
  6    67 ms    66 ms    65 ms  ae1-500.cr1-stk3.ip4.gtt.net [77.67.90.96]
  7    76 ms    76 ms    76 ms  cloudflare-gw.cr0-stk3.ip4.gtt.net [141.136.101.178]
  8    75 ms    75 ms    74 ms  one.one.one.one [1.1.1.1]

Трассировка завершена.
```
- местоположение узлов  

|   Узел  |   Местоположенеи  |
|:-------:|:-----------------:|
|192.168.1.1|Краснодар|
|178.34.128.7|Ставрополь|
|178.34.130.6|Ставрополь|
|178.34.130.154|Ставрополь|
|77.67.90.97|Ирландия|
|77.67.90.96|Ирландия|
|141.136.101.178|Париж|
|1.1.1.1|Австралия|


- организации


|   Узел  |   Организация     |
|:-------:|:-----------------:|
|192.168.1.1|ROSTELECOM|
|178.34.128.7|ROSTELECOM|
|178.34.130.6|ROSTELECOM|
|178.34.130.154|ROSTELECOM|
|77.67.90.97|Tinet International Network|
|77.67.90.96|Tinet International Network|
|141.136.101.178|Tinet International Network|
|1.1.1.1|APNIC and Cloudflare DNS|


- среднее RTT к DNS-серверу  

```
>ping 1.1.1.1

Обмен пакетами с 1.1.1.1 по с 32 байтами данных:
Ответ от 1.1.1.1: число байт=32 время=74мс TTL=59
Ответ от 1.1.1.1: число байт=32 время=65мс TTL=59
Ответ от 1.1.1.1: число байт=32 время=64мс TTL=59
Ответ от 1.1.1.1: число байт=32 время=121мс TTL=59

Статистика Ping для 1.1.1.1:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 64мсек, Максимальное = 121 мсек, Среднее = 81 мсек
```

- наибольшую временную задержку при передаче вносит 2-й, 5-й узел.





3) **OpenDNS - 208.67.222.222**  

- маршрут 
```
>tracert 208.67.222.222

Трассировка маршрута к resolver1.opendns.com [208.67.222.222]
с максимальным числом прыжков 30:

  1     3 ms    12 ms     1 ms  TP-LINK.Home [192.168.1.1]
  2    25 ms    24 ms    24 ms  krdr-bras4.ug.ip.rostelecom.ru [178.34.128.7]
  3    25 ms    31 ms    33 ms  178.34.130.6
  4    67 ms    67 ms    72 ms  87.226.133.59
  5    71 ms    67 ms   123 ms  ae1-500.cr1-stk3.ip4.gtt.net [77.67.90.96]
  6    90 ms    89 ms    89 ms  ae13.cr5-ams1.ip4.gtt.net [213.200.117.202]
  7    94 ms    94 ms    94 ms  opendns-gw.ip4.gtt.net [77.67.66.70]
  8    94 ms    95 ms    93 ms  resolver1.opendns.com [208.67.222.222]

Трассировка завершена.
```
- местоположение узлов  

|   Узел  |   Местоположенеи  |
|:-------:|:-----------------:|
|192.168.1.1|Краснодар|
|178.34.128.7|Ставрополь|
|178.34.130.6|Ставрополь|
|87.226.133.59|Москва|
|77.67.90.96|Ирландия|
|213.200.117.202|США|
|77.67.66.70|Ирландия|
|208.67.222.222|San Francisco|
 

- организации

|   Узел  |   Организация     |
|:-------:|:-----------------:|
|192.168.1.1|ROSTELECOM|
|178.34.128.7|ROSTELECOM|
|178.34.130.6|ROSTELECOM|
|87.226.133.59|JSC Rostelecom|
|77.67.90.96|Tinet International Network|
|213.200.117.202|GTT|
|77.67.66.70|Tiscali International Network B.V.|
|208.67.222.222|Cisco OpenDNS, LLC|
  

- среднее RTT к DNS-серверу  

```
>ping 208.67.222.222

Обмен пакетами с 208.67.222.222 по с 32 байтами данных:
Ответ от 208.67.222.222: число байт=32 время=91мс TTL=58
Ответ от 208.67.222.222: число байт=32 время=90мс TTL=58
Ответ от 208.67.222.222: число байт=32 время=90мс TTL=58
Ответ от 208.67.222.222: число байт=32 время=91мс TTL=58

Статистика Ping для 208.67.222.222:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 90мсек, Максимальное = 91 мсек, Среднее = 90 мсек
```

- наибольшую временную задержку при передаче вносит 2-й и 4-й узел.  

4) **Ростелеком МРФ "ЮГ" - 85.175.46.122**
- маршрут 
```
>tracert 85.175.46.122

Трассировка маршрута к rdns1.kes.ru [85.175.46.122]
с максимальным числом прыжков 30:

  1     2 ms     1 ms     2 ms  TP-LINK.Home [192.168.1.1]
  2    32 ms    25 ms    24 ms  krdr-bras4.ug.ip.rostelecom.ru [178.34.128.7]
  3    35 ms    46 ms    24 ms  83.239.110.109
  4    37 ms    23 ms    37 ms  rdns1.kes.ru [85.175.46.122]

Трассировка завершена.
```
- местоположение узлов  

|   Узел  |   Местоположенеи  |
|:-------:|:-----------------:|
|192.168.1.1|Краснодар|
|178.34.128.7|Ставрополь|
|83.239.110.109|Краснодар|
|85.175.46.122|Краснодар|

 

- организации

|   Узел  |   Организация     |
|:-------:|:-----------------:|
|192.168.1.1|ROSTELECOM|
|178.34.128.7|ROSTELECOM|
|83.239.110.109|JSC Rostelecom Macroregional Branch South|
|85.175.46.122|JSC Rostelecom Macroregional Branch South|


- среднее RTT к DNS-серверу  

```
>ping 85.175.46.122

Обмен пакетами с 85.175.46.122 по с 32 байтами данных:
Ответ от 85.175.46.122: число байт=32 время=33мс TTL=60
Ответ от 85.175.46.122: число байт=32 время=24мс TTL=60
Ответ от 85.175.46.122: число байт=32 время=24мс TTL=60
Ответ от 85.175.46.122: число байт=32 время=91мс TTL=60

Статистика Ping для 85.175.46.122:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 24мсек, Максимальное = 91 мсек, Среднее = 43 мсек
```

- наибольшую временную задержку при передаче вносит 2-й узел.


#### **Сравнительная диаграмма RTT к серверам**

```{r cache=TRUE}
library("ggplot2")
df = read.csv(file = "RTT.csv")
ggplot(data = df, aes(x = DNS, y = rtt, fill = DNS)) + geom_bar(stat = "identity") + 
coord_flip() +
geom_text(aes(label = rtt)) + theme_classic()
```

Как мы видим на графике, наименьше RTT(временя передачи сигнала между двумя точками) наблюдается к DHC-серверу моего провайдера, Ростелеком МРФ "ЮГ". Наибольшее к OpenDNS.

Наибольшую временную задержку при передаче вносит 2-й узел, это krdr-bras4.ug.ip.rostelecom.ru [178.34.128.7] - узел моего провайдера. Он играет важную роль, так как все соеденения идут через него.

### **Вывод**
Мы познакомились с различными DNS-серверами, научились анализировать сетевые параметры, полученные при работе с командой tracert, которая предназначенна для определения маршрутов следования данных до указаного узла. Научились определять качество соеденения между двумя узлами в сети. 



